### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by kierandrewett** [Blueyescat/image.sk#1]
I'm trying to basically use a image and put a variable on top? So for example, i want it to look like this 
http://i-hate.ender.site/i/cMuMZo.png

**Comment by kierandrewett** [comment]
So I want the [PLAYERNAME HERE] to be %player%,any help?

**Comment by Blueyescat** [comment]
Make an image text using the [create image text](https://github.com/Blueyescat/image.sk/wiki/Documentation#create-image-text) effect with text **`player's name`**, then write it on the image using the [write text](https://github.com/Blueyescat/image.sk/wiki/Documentation#write-text) effect.

If you meant to have a placeholder on the image, no that is not possible.

```vb
on load:
	get image from file "images/welcome message.png" and store it in {images::welcomeMessage}

# ... :	
	create an image text with id "username" with text player's name
	set font of "username" to "Arial"
	set bold state of "username" to on
	set size of "username" to 48
	set color of "username" to color from rgb 99, 54, 190
	
	set {_image} to a copy of {images::welcomeMessage}
	write image text with id "username" on {_image} at location 52, 146
	delete image text with id "username"
	
	# and use {_image}
```
So you would remove the "[PLAYERNAME HERE]" part from the image and put it to **`images`** folder in your server folder. Then it would be a template, and you can write the player name using image.sk. Of  course you can also make whole the image yourself using image.sk.

You can use the [register font](https://github.com/Blueyescat/image.sk/wiki/Documentation#register-font) effect to register a new font.

**Comment by kierandrewett** [comment]
I'll try this ty.

**Comment by EnderDev** [comment]
Could you tell me where I would make the images folder? Plugins folder or what?

**Comment by kierandrewett** [comment]
https://hastebin.com/fewujijise.sql

https://hastebin.com/ikimabasej.sql

This doesn't seem to work, any ideas?

**Comment by Blueyescat** [comment]
Because Vixio's upload effect isn't mean to convert string representation of a [BufferedImage](https://docs.oracle.com/javase/8/docs/api/java/awt/image/BufferedImage.html) to an image and upload it. You have to [save](https://github.com/Blueyescat/image.sk/wiki/Documentation#save-image) the image to a file and upload it.

Also why would you enter an URL to a "register font from **file**" effect 🙁 Currently there is no support for registering font from URL.

**Comment by kierandrewett** [comment]
Hi, I am still having issues with this.

**Comment by HardstylesDev** [comment]
I'm trying to get into this thing, however seem to get errors while loading it. I have skript-mirror installed so i don't think that this is the issue https://hastebin.com/ofozixulak.shell

**Comment by Blueyescat** [comment]
@EnderDev?

@GetRektTom You probably have an old version of skript-mirror. https://github.com/btk5h/skript-mirror/releases
Also please open a new issue for different problems next time.
