### ISSUE TITLE
Issue on write any text on image

### ISSUE THREAD

**Issue by kvsilva** [Blueyescat/image.sk#2]
I'm having a problem with image.sk, using the given memes example, I can not write anything on it. 

My Server Plugins: Skript, WildSkript, PlaceholderAPI, skUtilities, Reqn, SkQuery, skript-mirror, TwitterSK, SkriptJSON, Vault, ProtocolLib, Skellett, skript-yam

**Comment by Blueyescat** [comment]
So the output image doesn't have any text on it? Can you send the code you used?

**Comment by Blueyescat** [comment]
Nevermind, i found and fixed the problem. It was a too small but too important mistake. Thanks for reporting!

Also please re-copy the meme generator code, i have edited it to don't conflict with Vixio's width/height syntaxes.

https://github.com/Blueyescat/image.sk/blob/master/!image.sk
https://github.com/Blueyescat/image.sk/wiki/Examples#example-2---meme-generator
