### ISSUE TITLE
Issue on Reload Script

### ISSUE THREAD

**Issue by kvsilva** [Blueyescat/image.sk#3]
I always put the code and give reload in the script to reload it, I get this error in the console: https://hastebin.com/efuvexuxag.md (The code is what image.sk without any change.)

**Comment by Blueyescat** [comment]
Update your Skript, dev27 is already broken. https://github.com/SkriptLang/Skript/releases/tag/dev37c
dev37 works on 1.8 but not supported.

**Comment by Blueyescat** [comment]
no response
